In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/train.csv")

In [3]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
###Drop Nan Values
df=df.dropna()

In [5]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [6]:
## Get the Dependent features
y=df['label']

In [7]:
X.shape

(18285, 4)

In [8]:
y.shape

(18285,)

In [9]:
import tensorflow as tf

In [10]:
tf.__version__

'2.12.0'

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [12]:
### Vocabulary size
voc_size=5000

# Onehot Representation

In [13]:
messages=X.copy()

In [14]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [15]:
messages.reset_index(inplace=True)


In [16]:
import nltk
import re
from nltk.corpus import stopwords

In [17]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [18]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [19]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [20]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[656, 3579, 305, 2104, 2168, 1643, 4405, 81, 4203, 2363],
 [2223, 23, 177, 2618, 2068, 1924, 4104],
 [4070, 519, 1376, 184],
 [920, 3967, 2120, 1290, 2320, 4843],
 [3804, 2068, 3772, 4318, 4035, 2906, 2068, 4455, 4612, 2514],
 [1357,
  801,
  140,
  2409,
  333,
  1765,
  4695,
  3230,
  3123,
  166,
  89,
  4548,
  424,
  1154,
  4104],
 [1843, 1646, 19, 4351, 3592, 420, 4653, 165, 1770, 2766, 1071],
 [4817, 988, 4805, 1326, 4022, 2262, 1765, 3096, 1770, 2766, 1071],
 [4298, 1121, 1203, 1188, 1356, 2518, 1372, 4365, 1765, 724],
 [4229, 62, 2042, 4746, 800, 3310, 173, 250],
 [441, 1496, 1243, 438, 2000, 3325, 3996, 2555, 2673, 4158, 2032],
 [1290, 1840, 2168, 2518, 1765, 4022],
 [3968, 361, 1733, 3314, 254, 598, 3562, 1897, 1052],
 [2954, 3560, 2145, 1737, 1906, 3983, 1271, 1770, 2766, 1071],
 [962, 2334, 4326, 4712, 3789, 1770, 2766, 1071],
 [4069, 4368, 1655, 607, 1878, 3986, 2791, 3210, 1046, 427],
 [653, 838, 23],
 [317, 606, 2447, 4276, 1765, 1820, 522, 4104],
 [4393, 4300, 177, 

# Embedding Representation

In [21]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...   81 4203 2363]
 [   0    0    0 ... 2068 1924 4104]
 [   0    0    0 ...  519 1376  184]
 ...
 [   0    0    0 ... 1770 2766 1071]
 [   0    0    0 ... 3022 1475 1927]
 [   0    0    0 ... 4206 4157 1490]]


In [22]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,  656,
       3579,  305, 2104, 2168, 1643, 4405,   81, 4203, 2363], dtype=int32)

In [23]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [24]:
len(embedded_docs),y.shape

(18285, (18285,))

In [25]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [26]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

# Model Training

In [28]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 13s 55ms/step - loss: 0.3291 - accuracy: 0.8478 - val_loss: 0.1895 - val_accuracy: 0.9168
Epoch 2/10
192/192 [==============================] - 10s 50ms/step - loss: 0.1345 - accuracy: 0.9473 - val_loss: 0.2043 - val_accuracy: 0.9200
Epoch 3/10
192/192 [==============================] - 9s 46ms/step - loss: 0.0949 - accuracy: 0.9651 - val_loss: 0.2200 - val_accuracy: 0.9125
Epoch 4/10
192/192 [==============================] - 12s 64ms/step - loss: 0.0752 - accuracy: 0.9739 - val_loss: 0.2668 - val_accuracy: 0.9181
Epoch 5/10
192/192 [==============================] - 10s 51ms/step - loss: 0.0549 - accuracy: 0.9820 - val_loss: 0.2976 - val_accuracy: 0.9157
Epoch 6/10
192/192 [==============================] - 9s 47ms/step - loss: 0.0402 - accuracy: 0.9858 - val_loss: 0.3023 - val_accuracy: 0.9084
Epoch 7/10
192/192 [==============================] - 12s 62ms/step - loss: 0.0264 - accuracy: 0.9919 - val_loss: 0.4101 - val_accuracy: 0

# Adding Dropout


In [29]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

# Performance Metrics And Accuracy

In [31]:
y_pred=model.predict(X_test)

189/189 [==============================] - 2s 7ms/step


In [45]:
import sklearn.metrics as sm
print("Mean absolute error =", round(sm.mean_absolute_error(y_test, y_pred), 2)) 
print("Mean squared error =", round(sm.mean_squared_error(y_test, y_pred), 2)) 
print("Median absolute error =", round(sm.median_absolute_error(y_test, y_pred), 2)) 
print("Explain variance score =", round(sm.explained_variance_score(y_test, y_pred), 2)) 
print("R2 score =", round(sm.r2_score(y_test, y_pred), 2))

Mean absolute error = 0.5
Mean squared error = 0.25
Median absolute error = 0.5
Explain variance score = -0.0
R2 score = -0.02
